language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

install:
  - go get -t -v .

script:
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic ./asdu ./cs104

after_success:
  - bash <(curl -s https://codecov.io/bash)